#!/usr/bin/env python3
"""
Shared Sprite Maps and Game Display Names for Data Scripts
"""

from typing import Dict, Any

GAME_VERSION_MAP: Dict[str, Dict[str, Any]] = {
    "red":               {"gen": "generation-i",   "sprite_key": "red-blue",                    "sprite_dir": "red-blue",                    "gen_num": 1},
    "blue":              {"gen": "generation-i",   "sprite_key": "red-blue",                    "sprite_dir": "red-blue",                    "gen_num": 1},
    "yellow":            {"gen": "generation-i",   "sprite_key": "yellow",                      "sprite_dir": "yellow",                      "gen_num": 1},
    "gold":              {"gen": "generation-ii",  "sprite_key": "gold",                        "sprite_dir": "gold",                        "gen_num": 2},
    "silver":            {"gen": "generation-ii",  "sprite_key": "silver",                      "sprite_dir": "silver",                      "gen_num": 2},
    "crystal":           {"gen": "generation-ii",  "sprite_key": "crystal",                     "sprite_dir": "crystal",                     "gen_num": 2},
    "ruby":              {"gen": "generation-iii", "sprite_key": "ruby-sapphire",               "sprite_dir": "ruby-sapphire",               "gen_num": 3},
    "sapphire":          {"gen": "generation-iii", "sprite_key": "ruby-sapphire",               "sprite_dir": "ruby-sapphire",               "gen_num": 3},
    "emerald":           {"gen": "generation-iii", "sprite_key": "emerald",                     "sprite_dir": "emerald",                     "gen_num": 3},
    "firered":           {"gen": "generation-iii", "sprite_key": "firered-leafgreen",           "sprite_dir": "firered-leafgreen",           "gen_num": 3},
    "leafgreen":         {"gen": "generation-iii", "sprite_key": "firered-leafgreen",           "sprite_dir": "firered-leafgreen",           "gen_num": 3},
    "diamond":           {"gen": "generation-iv",  "sprite_key": "diamond-pearl",              "sprite_dir": "diamond-pearl",              "gen_num": 4},
    "pearl":             {"gen": "generation-iv",  "sprite_key": "diamond-pearl",              "sprite_dir": "diamond-pearl",              "gen_num": 4},
    "platinum":          {"gen": "generation-iv",  "sprite_key": "platinum",                   "sprite_dir": "platinum",                   "gen_num": 4},
    "heartgold":         {"gen": "generation-iv",  "sprite_key": "heartgold-soulsilver",       "sprite_dir": "heartgold-soulsilver",      "gen_num": 4},
    "soulsilver":        {"gen": "generation-iv",  "sprite_key": "heartgold-soulsilver",       "sprite_dir": "heartgold-soulsilver",      "gen_num": 4},
    "black":             {"gen": "generation-v",   "sprite_key": "black-white",                "sprite_dir": "black-white",               "gen_num": 5},
    "white":             {"gen": "generation-v",   "sprite_key": "black-white",                "sprite_dir": "black-white",               "gen_num": 5},
    "black-2":           {"gen": "generation-v",   "sprite_key": "black-white",                "sprite_dir": "black-white",               "gen_num": 5},
    "white-2":           {"gen": "generation-v",   "sprite_key": "black-white",                "sprite_dir": "black-white",               "gen_num": 5},
    "x":                 {"gen": "generation-vi",  "sprite_key": "x-y",                         "sprite_dir": "x-y",                       "gen_num": 6},
    "y":                 {"gen": "generation-vi",  "sprite_key": "x-y",                         "sprite_dir": "x-y",                       "gen_num": 6},
    "omega-ruby":        {"gen": "generation-vi",  "sprite_key": "omegaruby-alphasapphire",    "sprite_dir": "omegaruby-alphasapphire",   "gen_num": 6},
    "alpha-sapphire":    {"gen": "generation-vi",  "sprite_key": "omegaruby-alphasapphire",    "sprite_dir": "omegaruby-alphasapphire",   "gen_num": 6},
    "sun":               {"gen": "generation-vii", "sprite_key": "ultra-sun-ultra-moon",        "sprite_dir": "ultra-sun-ultra-moon",      "gen_num": 7},
    "moon":              {"gen": "generation-vii", "sprite_key": "ultra-sun-ultra-moon",        "sprite_dir": "ultra-sun-ultra-moon",      "gen_num": 7},
    "ultra-sun":         {"gen": "generation-vii", "sprite_key": "ultra-sun-ultra-moon",        "sprite_dir": "ultra-sun-ultra-moon",      "gen_num": 7},
    "ultra-moon":        {"gen": "generation-vii", "sprite_key": "ultra-sun-ultra-moon",        "sprite_dir": "ultra-sun-ultra-moon",      "gen_num": 7},
    "sword":             {"gen": "generation-viii","sprite_key": None,                          "sprite_dir": None,                         "gen_num": 8},
    "shield":            {"gen": "generation-viii","sprite_key": None,                          "sprite_dir": None,                         "gen_num": 8},
    "brilliant-diamond": {"gen": "generation-viii","sprite_key": "brilliant-diamond-shining-pearl", "sprite_dir": "brilliant-diamond-shining-pearl", "gen_num": 8},
    "shining-pearl":     {"gen": "generation-viii","sprite_key": "brilliant-diamond-shining-pearl", "sprite_dir": "brilliant-diamond-shining-pearl", "gen_num": 8},
    "legends-arceus":    {"gen": "generation-viii","sprite_key": None,                          "sprite_dir": None,                         "gen_num": 8},
    "scarlet":           {"gen": "generation-ix",  "sprite_key": "scarlet-violet",             "sprite_dir": "scarlet-violet",            "gen_num": 9},
    "violet":            {"gen": "generation-ix",  "sprite_key": "scarlet-violet",             "sprite_dir": "scarlet-violet",            "gen_num": 9},
}

STANDARD_VARIANTS = ["front_default", "front_shiny", "back_default", "back_shiny"]
GEN5_GAMES = {"black", "white", "black-2", "white-2"}

GAME_DISPLAY_NAMES: Dict[str, str] = {
    "red": "Pokémon Red",
    "blue": "Pokémon Blue",
    "yellow": "Pokémon Yellow",
    "gold": "Pokémon Gold",
    "silver": "Pokémon Silver",
    "crystal": "Pokémon Crystal",
    "ruby": "Pokémon Ruby",
    "sapphire": "Pokémon Sapphire",
    "emerald": "Pokémon Emerald",
    "firered": "Pokémon FireRed",
    "leafgreen": "Pokémon LeafGreen",
    "diamond": "Pokémon Diamond",
    "pearl": "Pokémon Pearl",
    "platinum": "Pokémon Platinum",
    "heartgold": "Pokémon HeartGold",
    "soulsilver": "Pokémon SoulSilver",
    "black": "Pokémon Black",
    "white": "Pokémon White",
    "black-2": "Pokémon Black 2",
    "white-2": "Pokémon White 2",
    "x": "Pokémon X",
    "y": "Pokémon Y",
    "omega-ruby": "Omega Ruby",
    "alpha-sapphire": "Alpha Sapphire",
    "sun": "Pokémon Sun",
    "moon": "Pokémon Moon",
    "ultra-sun": "Ultra Sun",
    "ultra-moon": "Ultra Moon",
    "sword": "Pokémon Sword",
    "shield": "Pokémon Shield",
    "brilliant-diamond": "Brilliant Diamond",
    "shining-pearl": "Shining Pearl",
    "legends-arceus": "Legends: Arceus",
    "scarlet": "Pokémon Scarlet",
    "violet": "Pokémon Violet",
}
